--- !ruby/object:RI::ClassDescription 
attributes: []

class_methods: []

comment: 
constants: []

full_name: Application
includes: []

instance_methods: []

name: Application
superclass: Merb::Controller
